import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {NuqsAdapter} from "nuqs/adapters/next/app"

import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'

import { Toaster } from "@/components/ui/sonner";


import "./globals.css";
import { ConvexClientProvider } from "@/components/convex-client-provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Blu Editor",
  description: "Generated by Stijn Walravens",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
      <body
        className={inter.className}
      >
        <NuqsAdapter>
          <ConvexClientProvider>
            <Toaster />
            {children}
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
    </ClerkProvider>
  );
}
